### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in ...\no-db-cms\admin\page_add.php on line 64

### ISSUE THREAD

**Issue by wtfz** [kidino/no-db-cms#1]
```
$error = false;

if (isset($error)) { // return TRUE if $error = FALSE
   foreach($error as $e) {
```

Testing submit issue :smile: Warning yang sama pada **page_edit.php**

**Comment by syaifulsz** [comment]
This PR should fixed the issue.
https://github.com/kidino/no-db-cms/pull/2

**Comment by wtfz** [comment]
Does $error used for other purpose besides isset()? If no, removing just '$error = false' should do the trick I guess.

**Comment by kidino** [comment]
pull request accepted for now. but $error = false is removed in next push.
